### ISSUE TITLE
Simplify travel_mode_callback function

### ISSUE THREAD

**Issue by savannahrussell** [alyraptor/acf-polyline#4]
Function: https://github.com/alyraptor/acf-polyline/blob/9392fba0622ea85ea214151af1a2f338d9bc1e02/options.php#L115

This could be made into a foreach loop that passes in an array of travel modes. That could reduce the amount of times `$selected` is set/checked against and make it easier to add to, in case Google adds another travel mode, like Quad Skate 😉

**Comment by alyraptor** [comment]
Fixed with https://github.com/alyraptor/acf-polyline/commit/7d0873c195d813bde99970998dd12de19631dae6
