### ISSUE TITLE
Event Listeners set to `click` need to be set to `click tap touch`

### ISSUE THREAD

**Issue by savannahrussell** [alyraptor/acf-polyline#5]
https://github.com/alyraptor/acf-polyline/blob/9392fba0622ea85ea214151af1a2f338d9bc1e02/assets/js/input.js#L27

We need to not make assumptions as to what devices users are using with our code. Adding those extra event listeners should catch most inputs.

**Comment by alyraptor** [comment]
Fixed with https://github.com/alyraptor/acf-polyline/commit/9ab8df5c9625a5c62c3acca3e3c36c83b2fd160e
