### ISSUE TITLE
Swap out links that go nowhere and act like buttons for buttons

### ISSUE THREAD

**Issue by savannahrussell** [alyraptor/acf-polyline#6]
https://github.com/alyraptor/acf-polyline/blob/9392fba0622ea85ea214151af1a2f338d9bc1e02/assets/js/input.js#L317

For accessibility and semantics reasons, keep in mind:

- if you click it and it takes you somewhere else, it's a link
- if you click it and it triggers something on the same page, it's a button

There are always caveats, of course, but that will get you through 98% of your cases.

**Comment by alyraptor** [comment]
Good accessibility improvement 👍

**Comment by alyraptor** [comment]
Fixed with https://github.com/alyraptor/acf-polyline/commit/433bbf9593294879281ce918d2f35cfcea0dc004
